### PR TITLE
Basic configuration & authentication setup

### PR DESCRIPTION
**Pull request by marcamillion**
I have done basic config & authentication.

Still working through setting up full authentication and testing for verification of the single-access token that should be returned by the API.

So this is a WIP.

### CODE REVIEW

**Comment by marcamillion** [comment]
@rkcudjoe How do I test the response of the endpoint without a valid SSL cert? I have directed Faraday not to verify my local cert by doing `@connection ||= Faraday.new(ssl: {verify: false}) do |f|`, but the issue I am running into is the response from Launch27.

This is the response object I get back:

```
ry(#<RSpec::ExampleGroups::Launch27Client::Authorization>)> res
=> #<Faraday::Response:0x007fda8b884100
 @env=
  #<struct Faraday::Env
   method=:post,
   body="<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n",
   url=#<URI::HTTPS https://acme-sandbox.l27.co/api/auth?email=some.email.com&password=some.valid.password>,
   request=#<struct Faraday::RequestOptions params_encoder=nil, proxy=nil, bind=nil, timeout=nil, open_timeout=nil, boundary=nil, oauth=nil>,
   request_headers={"User-Agent"=>"Launch27 v0.1.0", "Content-Type"=>"application/json", "Accept"=>"application/launch27.v2", "X-API-Key"=>"valid_api_key", "Content-Length"=>"0"},
   ssl=#<struct Faraday::SSLOptions verify=false, ca_file=nil, ca_path=nil, verify_mode=nil, cert_store=nil, client_cert=nil, client_key=nil, certificate=nil, private_key=nil, verify_depth=nil, version=nil>,
   parallel_manager=nil,
   params=nil,
   response=#<Faraday::Response:0x007fda8b884100 ...>,
   response_headers={"server"=>"nginx", "date"=>"Mon, 01 Aug 2016 06:03:15 GMT", "content-type"=>"text/html", "content-length"=>"166", "connection"=>"close"},
   status=405>,
 @on_complete_callbacks=[]>

```

Thoughts on how best to approach this? Do I need to get a valid SSL cert to get proper responses from the endpoint? Or can they make an exception for my testing, or do they have a non `https` endpoint that I can test against?

**Comment by rkcudjoe** [comment]
@marcamillion I need sometime to look into this because I haven't encountered this before

**Comment by marcamillion** [comment]
How did you test the response for the HTTPS endpoint on Convertkit? Or did you not test the response?

With this one, I have to receive a `single_access_token`, so I do have to test it.

But take your time to look into it and let me know.

**Comment by rkcudjoe** [comment]
@marcamillion I thought response in this gem was a resource from Launch27

I didn't test HTTPS responses in ConvertKit. You might have to add a Faraday middleware.

**Comment by rkcudjoe** [comment]
@marcamillion I just took a loot at the problem and you don't need to test the response yet. You'll test the response object when you call specific end points. Let me know if you need help with anything else.

**Pull request merged**
